### ISSUE TITLE
BeerJS #1: Hopfenreich

### ISSUE THREAD

**Issue by Yunnii** [beerjs/berlin#2]
9 October 2019
[Hopfenreich](http://hopfenreich.de/)
[Sorauer Str. 31, 10997 Berlin](https://goo.gl/maps/yawpu6YnXVc6vQew5)
7:00 pm

If you come, let us know by commenting the issue.

**Comment by spaguette** [comment]
Yes

**Comment by Yunnii** [comment]
🐝

**Comment by mk0x9** [comment]
👋🏽

**Comment by sameoldmadness** [comment]
:shipit:

**Comment by Yunnii** [comment]
Спасибо всем, кто пришел. Обсудили работу в Яндексе и 2Gis-e, чем отличается процесс разработки русских компаний от зарубежныx, подняли тему трекинга рабочих часов и скриншотов рабочего стола, а также как и куда смещен life/balance 

Ссылочки: 
- Контроль удаленных сотрудников в Crossover https://medium.com/@peshrus/control-of-remote-work-a38eef810b45
- Репа Frontend meetup https://github.com/beerjs/berlin

![photo_2019-10-15_12-52-49](https://user-images.githubusercontent.com/401584/66825635-efb8e100-ef4a-11e9-8984-cd5442e89167.jpg)
