### ISSUE TITLE
BeerJS #2: Hops & Barley

### ISSUE THREAD

**Issue by Yunnii** [beerjs/berlin#3]
23 October 2019
[Hops & Barley](http://www.hopsandbarley.eu)
[Wühlischstraße 22/23, 10245 Berlin](https://goo.gl/maps/tNNGCBHY2Dk7gH8g9)
7:00 pm

If you come, let us know by commenting the issue

**Comment by spaguette** [comment]
👍

**Comment by Yunnii** [comment]
Thanks to everyone who came and special thanks to those who brought colleagues and friends
We talked about hackoberfest, monoliths, and microservices, secure communication between, interviews and interviews and platforms for preparing for interviews, shared libraries, about communicating with colleagues and sports

![photo_2019-10-26_11-55-43](https://user-images.githubusercontent.com/401584/67620312-bc593a80-f805-11e9-8fa1-73cb1491f942.jpg)
![photo_2019-10-26_11-55-42](https://user-images.githubusercontent.com/401584/67620313-bc593a80-f805-11e9-8f56-a609971ea1dd.jpg)
![photo_2019-10-25_15-09-52](https://user-images.githubusercontent.com/401584/67620314-bcf1d100-f805-11e9-9271-9a925d720d29.jpg)
